# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Sahma Workflow

on:
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]

jobs:
   test:
      strategy:
         matrix:
            os: [ubuntu-latest, macos-latest]
            go: ["1.23"]
            test-tags:
               [
                  "",
                  "-tags nomsgpack",
                  '-tags "sonic avx"',
                  "-tags go_json",
                  "-race",
               ]
            include:
               - os: ubuntu-latest
                 go-build: ~/.cache/go-build
               - os: macos-latest
                 go-build: ~/Library/Caches/go-build
      name: ${{ matrix.os }} @ Go ${{ matrix.go }} ${{ matrix.test-tags }}
      runs-on: ${{ matrix.os }}
      env:
         GO111MODULE: on
         TESTTAGS: ${{ matrix.test-tags }}
      steps:
         - name: Set up Go ${{ matrix.go }}
           uses: actions/setup-go@v5
           with:
              go-version: ${{ matrix.go }}
              cache: false

         - name: Checkout Code
           uses: actions/checkout@v4

         - uses: actions/cache@v4
           with:
              path: |
                 ${{ matrix.go-build }}
                 ~/go/pkg/mod
              key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
              restore-keys: |
                 ${{ runner.os }}-go-

         - name: Run Tests
           run: make test
